{% set org = "tdegeus" %}
{% set name = "QPot" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 0727edc2eee4fd916da299fd68c2c6b972c4ad19089b1f02a77a413f5af78cc1

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - setuptools_scm
    - xtensor
  run:
    - xtensor

test:
  commands:
    - test -d ${PREFIX}/include/{{ name }}  # [unix]
    - test -f ${PREFIX}/include/{{ name }}/Static.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/{{ name }}/{{ name }}Config.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\{{ name }}\Static.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\{{ name }}Config.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/{{ org }}/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Library to keep track of a sequential potential energy landscape.
  description: Library to keep track of a sequential potential energy landscape.
  doc_url: https://{{ org }}.github.io/{{ name }}
  dev_url: https://github.com/{{ org }}/{{ name }}

extra:
  recipe-maintainers:
    - tdegeus
