{% set org = "tdegeus" %}
{% set name = "QPot" %}
{% set version = "0.9.4" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 59aa4eb956bca2133a32baa5568dbebc63f1ccf77ad74034f356064a25fad160

build:
  number: 0
  script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}

outputs:

  - name: {{ name|lower }}

    script: install.sh  # [unix]
    script: install.bat  # [win]

    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - make  # [unix]
      host:
        - setuptools_scm
        - xtensor
      run:
        - xtensor

    test:
      commands:
        - test -d ${PREFIX}/include/{{ name }}  # [unix]
        - test -f ${PREFIX}/include/{{ name }}/Chunked.hpp  # [unix]
        - test -f ${PREFIX}/lib/cmake/{{ name }}/{{ name }}Config.cmake  # [unix]
        - if exist %LIBRARY_PREFIX%\include\{{ name }}\Chunked.hpp (exit 0) else (exit 1)  # [win]
        - if exist %LIBRARY_PREFIX%\lib\cmake\{{ name }}Config.cmake (exit 0) else (exit 1)  # [win]

  - name: python-{{ name|lower }}

    script: install_python.sh  # [unix]
    script: install_python.bat  # [win]

    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - ninja
      host:
        - python
        - pip
        - setuptools_scm
        - pyxtensor
      run:
        - python

    test:
      imports:
        - {{ name }}
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://github.com/{{ org }}/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Library to keep track of a sequential potential energy landscape.
  description: Library to keep track of a sequential potential energy landscape.
  doc_url: https://{{ org }}.github.io/{{ name }}
  dev_url: https://github.com/{{ org }}/{{ name }}

extra:
  recipe-maintainers:
    - tdegeus
